INSERT INTO beers (category, beer_name, style, abv, description, brewery) VALUES
('American Macro Brew', 'Hamms', ' American Adjunct Lager', 4.6, '"If I was thirsty, I could consume this whole can in one fell swoop." It is a revelation.', 'Miller-Coors'),

('American Macro Brew', 'Coors Light', 'American Light Lager', 4.2, '12 ounce bottle poured into a thick plastic glass. Color of straw/hay. Smell faint pine needles. Taste is clean with no bitterness or aftertaste. Mouthfeel is crisp, watery, refreshing. I am well aware that a lot of beer snobs scoff at the idea of drinking Coors and Coors light but quite frankly I really dont give a shit what they think. To each their own. Personally I like coors. Its reasonably priced and the low calories/abv is a plus in my book. After a long day on the ranch I would enjoy a "Silver Bullet" over some overpriced high gravity IPA made who knows where. I would give Coors Light a solid A. Oh and it has the same abv as my other favorite beer Shiner Bock', 'Miller-Coors'),


('American Macro Brew', 'Budweiser', 'American Adjunct Lager', 5, 'The smell after opening a can or bottle of this is almost enough reason not to touch it. A horrendous waft of death in your face that slightly fades as time passes is the main thing you focus on for the first minute. After the death passes, the taste is slightly bitter grain that lingers for a second before disappearing into nothing. You take another sip, and the same thing happens, again and again till the bottle is gone. Pours almost clear, a nice mix of foam and carbonation, and a taste that isnt overall bad. Another plus is its slightly higher abv of 5% over most other light-weight beers. I wouldnt purchase for myself ever again, but neither would I turn my nose up at it if I were offered, its alright.', 'Anheuser-Busch'),

('American Macro Brew', 'Red Dog', 'American Adjunct Lager', 5, 'My story with Red Dog began a long while ago. It was a typical morning and I was headed to my local liquor store here in Rice Lake, WI, where I was planning on purchasing my usual 24 ounce miller lite. I had brought exact change to buy the Miller, but to my dismay, there had been a sudden increase in price of Miller and I no longer had enough for it. Because of this, I was forced to settle for a less expensive beer, and quickly took a Red Dog out of the cooler instead. I was disappointed while leaving the liquor store, but my sadness was quickly alleviated when I took my first sip of Red Dog. I found both its flavor and smoothness to be uncommon. Since then, I have not bought any other kind of beer. Red Dogs flavor is bold, yet smooth, and takes the edge off of a stressful morning at work. Red Dog is a beer that pairs perfectly with a nice carton of Marlboros and in my experience is best enjoyed early in the morning (around 8am. Red Dog is an overall flawless beer that perfectly embodies all qualities that an American stout should want to present.', 'Miller Brewing Co.'),

('American Macro Brew', 'Bud Light', 'American Light Lager', 4.2, 'Would never buy any, but if it were free, I would drink it.', 'Anheuser-Busch'),

('American Macro Brew', 'Miller High Life', 'American Adjunct Lager', 4.6, 'What else can I say, its the champagne of beers🤙', 'Miller Brewing Co.'),

('American Macro Brew', 'Miller Lite', 'American Light Lager', 4.1, '12oz can. Airplane beverage. Served into a plastic cup. Clear golden yellow body, one and half finger white head, good retention and lacing. Smell is watered down barley grain, slight sugar, and more water. Its not very aromatic, and the palate is pretty bland too. Its an inoffensive beer without much hop character or hop aromatics to it. Mouthfeel is light bodied, thin and watery, not much flavor or nuance on the backend.', 'Miller Brewing Co.'),

('American Macro Brew', 'Busch Light', 'American Light Lager', 4.1, 'It doesnt taste good, it tastes right.', 'Anheuser-Busch'),

('American Macro Brew', 'Keystone Light', 'American Light Lager', 4.1, 'This beer tastes like a whisper from an American Adjunct Lager from across a dirty old pool hall. And I dont hate that.', 'Coors Brewing Company (Molson-Coors)'),

('American Macro Brew', 'Natural Light', 'American Light Lager', 4.2, 'Best beer on the market. Youc can drink 2 or you can drink 20. This beer never quits being the most iconic symbol of fraternal bliss ever created', 'Anheuser-Busch');